/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boxing;

import java.util.Collections;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Acer
 */
public class POSFrame extends javax.swing.JFrame {

    /**
     * Creates new form POSFrame
     */
    
    LinkedList<Person> personlist;
    TableModel daftarmodel;
    int tes = 0;
    
    public POSFrame() {
        initComponents();
        personlist = new LinkedList<>();
        daftarmodel = daftarTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namatextfield = new javax.swing.JTextField();
        umurtextfield = new javax.swing.JTextField();
        berattextfield = new javax.swing.JTextField();
        tinggitextfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        daftarTable = new javax.swing.JTable();
        insertbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        umurbutton = new javax.swing.JButton();
        beratbutton = new javax.swing.JButton();
        tinggibutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setToolTipText("");

        namatextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatextfieldActionPerformed(evt);
            }
        });

        umurtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurtextfieldActionPerformed(evt);
            }
        });

        berattextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berattextfieldActionPerformed(evt);
            }
        });

        tinggitextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggitextfieldActionPerformed(evt);
            }
        });

        daftarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Umur", "Berat Badan", "Tinggi Badan"
            }
        ));
        jScrollPane2.setViewportView(daftarTable);

        insertbutton.setText("Insert");
        insertbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttonActionPerformed(evt);
            }
        });

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Weight");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Height");

        umurbutton.setText("Sort by Age");
        umurbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurbuttonActionPerformed(evt);
            }
        });

        beratbutton.setText("Sort by Weight");
        beratbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratbuttonActionPerformed(evt);
            }
        });

        tinggibutton.setText("Sort by Height");
        tinggibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggibuttonActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boxing/tes.jpeg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(insertbutton)
                                        .addGap(18, 18, 18)
                                        .addComponent(deletebutton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(umurtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                .addComponent(namatextfield))
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(tinggitextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(berattextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(32, 32, 32)))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(umurbutton)
                        .addGap(71, 71, 71)
                        .addComponent(beratbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tinggibutton)
                        .addGap(56, 56, 56)))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(berattextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(umurtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tinggitextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertbutton)
                            .addComponent(deletebutton))
                        .addGap(16, 16, 16)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurbutton)
                    .addComponent(beratbutton)
                    .addComponent(tinggibutton))
                .addGap(21, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namatextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatextfieldActionPerformed

    private void umurtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umurtextfieldActionPerformed

    private void berattextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berattextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berattextfieldActionPerformed

    private void tinggitextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggitextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggitextfieldActionPerformed
 private void clearInputFields() {
        namatextfield.setText("");
        umurtextfield.setText("");
        berattextfield.setText("");
        tinggitextfield.setText("");
    }
    private void insertbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttonActionPerformed
        // TODO add your handling code here:
            
        String nama = namatextfield.getText();
        int umur = Integer.parseInt(umurtextfield.getText());
        float berat = Float.parseFloat(berattextfield.getText());
        float tinggi = Float.parseFloat(tinggitextfield.getText());

        // Buat objek Person baru dan atur nilai atributnya
        Person person = new Person();
        person.nama = nama;
        person.umur = umur;
        person.berat = berat;
        person.tinggi = tinggi;
        
        int index = Collections.binarySearch(personlist, person);
        if (index < 0) {
            index = -(index + 1);
        }

        
        personlist.add(index,person);
        
        DefaultTableModel model = (DefaultTableModel) daftarTable.getModel();
        model.insertRow(index, new Object[]{nama, umur, berat, tinggi});

    
        daftarTable.setModel(model);
        
        tes++;
        clearInputFields();
        
        
        
    }//GEN-LAST:event_insertbuttonActionPerformed
    
    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        int lastindex = personlist.size() -1;
        int selectedRow = daftarTable.getSelectedRow();
        if (selectedRow >= 0 && selectedRow <= lastindex) {
        String nama = (String) daftarTable.getValueAt(selectedRow, 0);
        int umur = (int) daftarTable.getValueAt(selectedRow, 1);
        float berat = (float) daftarTable.getValueAt(selectedRow, 2);
        float tinggi = (float) daftarTable.getValueAt(selectedRow, 3);

        Person person = new Person();
        person.nama = nama;
        person.umur = umur;
        person.berat = berat;
        person.tinggi = tinggi;

        int index = Collections.binarySearch(personlist, person);
        if (index >= 0) {
            personlist.remove(index);
            DefaultTableModel model = (DefaultTableModel) daftarTable.getModel();
            model.removeRow(selectedRow);
            System.out.println("Data dihapus dari Linked List dan JTable");
        } else {
            System.out.println("Data tidak ditemukan di Linked List");
        }
    } else {
        System.out.println("Tidak ada data yang dipilih di JTable");
    }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void umurbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurbuttonActionPerformed
        // TODO add your handling code here:
        int n = personlist.size();
        for (int i = 0; i < n - 1; i++) {
        int maxIndex = i;
        for (int j = i + 1; j < n; j++) {
            if (personlist.get(j).umur > personlist.get(maxIndex).umur) {
                maxIndex = j;
            }
        }
        // Tukar elemen pada indeks i dengan elemen pada indeks maxIndex
        Person temp = personlist.get(i);
        personlist.set(i, personlist.get(maxIndex));
        personlist.set(maxIndex, temp);
    }

    // Memperbarui tampilan JTable dengan data yang telah diurutkan
    DefaultTableModel model = (DefaultTableModel) daftarTable.getModel();
    model.setRowCount(0); // Menghapus semua baris yang ada pada tabel

    int rowIndex = 0;
    for (Person person : personlist) {
        model.addRow(new Object[]{person.nama, person.umur, person.berat, person.tinggi});
        rowIndex++;
    }

    daftarTable.setModel(model);
    }//GEN-LAST:event_umurbuttonActionPerformed

    private void beratbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratbuttonActionPerformed
        // TODO add your handling code here:
        int n = personlist.size();
        for (int i = 0; i < n - 1; i++) {
        int maxIndex = i;
        for (int j = i + 1; j < n; j++) {
            if (personlist.get(j).berat > personlist.get(maxIndex).berat) {
                maxIndex = j;
            }
        }
        // Tukar elemen pada indeks i dengan elemen pada indeks maxIndex
        Person temp = personlist.get(i);
        personlist.set(i, personlist.get(maxIndex));
        personlist.set(maxIndex, temp);
    }

    // Memperbarui tampilan JTable dengan data yang telah diurutkan
    DefaultTableModel model = (DefaultTableModel) daftarTable.getModel();
    model.setRowCount(0); // Menghapus semua baris yang ada pada tabel

    int rowIndex = 0;
    for (Person person : personlist) {
        model.addRow(new Object[]{person.nama, person.umur, person.berat, person.tinggi});
        rowIndex++;
    }

    daftarTable.setModel(model);
    }//GEN-LAST:event_beratbuttonActionPerformed

    private void tinggibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggibuttonActionPerformed
        // TODO add your handling code here:
        int n = personlist.size();
        for (int i = 0; i < n - 1; i++) {
        int maxIndex = i;
        for (int j = i + 1; j < n; j++) {
            if (personlist.get(j).tinggi > personlist.get(maxIndex).tinggi) {
                maxIndex = j;
            }
        }
        // Tukar elemen pada indeks i dengan elemen pada indeks maxIndex
        Person temp = personlist.get(i);
        personlist.set(i, personlist.get(maxIndex));
        personlist.set(maxIndex, temp);
    }

    // Memperbarui tampilan JTable dengan data yang telah diurutkan
    DefaultTableModel model = (DefaultTableModel) daftarTable.getModel();
    model.setRowCount(0); // Menghapus semua baris yang ada pada tabel

    int rowIndex = 0;
    for (Person person : personlist) {
        model.addRow(new Object[]{person.nama, person.umur, person.berat, person.tinggi});
        rowIndex++;
    }

    daftarTable.setModel(model);
    }//GEN-LAST:event_tinggibuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beratbutton;
    private javax.swing.JTextField berattextfield;
    private javax.swing.JTable daftarTable;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton insertbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namatextfield;
    private javax.swing.JButton tinggibutton;
    private javax.swing.JTextField tinggitextfield;
    private javax.swing.JButton umurbutton;
    private javax.swing.JTextField umurtextfield;
    // End of variables declaration//GEN-END:variables
}
